// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:89874248935:web:882131f44170c1d8939e42',
    messagingSenderId: '89874248935',
    projectId: 'practice-firebase-4d441',
    authDomain: 'practice-firebase-4d441.firebaseapp.com',
    storageBucket: 'practice-firebase-4d441.firebasestorage.app',
    measurementId: 'G-60DBF7C7NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:89874248935:android:23b7f437a154f0d9939e42',
    messagingSenderId: '89874248935',
    projectId: 'practice-firebase-4d441',
    storageBucket: 'practice-firebase-4d441.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:89874248935:ios:b23a987e1b30b981939e42',
    messagingSenderId: '89874248935',
    projectId: 'practice-firebase-4d441',
    storageBucket: 'practice-firebase-4d441.firebasestorage.app',
    iosBundleId: 'com.maju.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:89874248935:ios:6a7b08aab10bb7e7939e42',
    messagingSenderId: '89874248935',
    projectId: 'practice-firebase-4d441',
    storageBucket: 'practice-firebase-4d441.firebasestorage.app',
    iosBundleId: 'com.maju',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:89874248935:web:25107bc537869819939e42',
    messagingSenderId: '89874248935',
    projectId: 'practice-firebase-4d441',
    authDomain: 'practice-firebase-4d441.firebaseapp.com',
    storageBucket: 'practice-firebase-4d441.firebasestorage.app',
    measurementId: 'G-24JP39NPYK',
  );
}
